# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e68fd4f295649b1076135936f7c552cd71479be5d581114ba0d34313713425c943d328d27d27a6be471b0439473170d4d22f54127c27b89d02fe95a3e83a9a61

test:
  secret_key_base: 0dd2e3ea30f88e4b592b8dbeba32100b12b22dc443ad8f40437b26630d96e9fb5398da9a5fbd97fd55c9e952a083f909446834c2813fb6b8624a3ea0c90b40cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
